# Generated by Django 3.2 on 2021-04-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=64)),
                ('nome', models.CharField(max_length=254)),
                ('endereco', models.CharField(max_length=254)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=254)),
                ('bairro', models.CharField(max_length=64)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=64)),
                ('estado', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=254)),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
