# Generated by Django 3.2 on 2021-04-08 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='login',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='senha',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
