# Generated by Django 3.2 on 2021-04-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210408_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=62),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(max_length=8),
        ),
    ]
